 export const EmployeeData = [
    {
        id:1,
        firstName:'Ali',
        lastName:'HAider',
        age:20
    },
    {
        id:2,
        firstName:'Aliyan',
        lastName:'Fazal',
        age:23
    },
    {
        id:3,
        firstName:'Ahmad',
        lastName:'Yameen',
        age:25
    },
]